// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbvnzztruplvbwkezryi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidm56enRydXBsdmJ3a2V6cnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjQwMDAsImV4cCI6MjA3MTA0MDAwMH0.0O9wPNC0vwkAc3CE0UghDQvAuB_yux2v3DkgX636oaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});